// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbwpxwzvfxbnplbhuybd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBid3B4d3p2ZnhibnBsYmh1eWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NjAzMTIsImV4cCI6MjA3MjQzNjMxMn0.n8kVOBmELXqs0dcuP4bbRE7UINM4aJYEOXDzkiybRKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});